### ISSUE TITLE
what about .net core? 

### ISSUE THREAD

**Issue by eitanh** [nicoriff/ORMi#7]
would like to know your opinion of remotely monitoring machines with .net core
please whatsapp me +972547377965 / eitan@securegion.com

**Comment by nicoriff** [comment]
Contact me: luque.nicolas@gmail.com

**Comment by lzinga** [comment]
Why was this done over email/phone call? Shouldn't this conversation of been done here so others can know indeed "what about .net core?"?

**Comment by nicoriff** [comment]
@lzinga This issue was open to see if some work was possible to be done with ORMi and involved some commercial work. ORMi is free and everyone can contribute. But my work isn't free.
As for .NET Core migration refers, It is in backlog to migrate to .NET Core. It requires quite an ammount of time. I think that in about 3 or 4 months I´ll release a .NET Core version. First, nevertheless will be making it to .NET Standard so at least will be compatible.

Thanks for visiting (and using?) ORMi.
